version: '3.8'

services:
  fcgi:
    container_name: my_container
    image: my_image:tag
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  nginx:
    container_name: my_nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    depends_on:
      - fcgi
